services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
    container_name: flask-scheduled-app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs 